[project]
name = "website"
version = "0.1.0"
description = "A simple website using SQL, SQLAlchemy, Flask, and React."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
]
